baseURL = "https://exec.awsbuilders.io/"
languageCode = "en-US"
defaultContentLanguage = "en"
googleAnalytics = "UA-41627770-2"
relativeURLs = true

title = "Building for Executives"
theme = "learn"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

uglyurls = true
sectionPagesMenu = "main"
pygmentsCodeFences = true
pygmentsStyle = "monokai"

[params]
  editURL = "https://github.com/MitchyBAwesome/aws-building-for-execs/edit/master/content/"
  description = "Building for Executives"
  author = "AWS"
  ghrepo = "https://github.com/MitchyBAwesome/aws-building-for-execs"
  disableBreadcrumb = false
  disableNextPrev = false
  themeVariant = "aws"
  disableSearch = false
  disableAssetsBusting = true
  disableLanguageSwitchingButton = false
  disableShortcutsTitle = true
  disableInlineCopyToClipBoard = true

[outputs]
home = [ "HTML", "RSS", "JSON"]

[blackfriday]
plainIDAnchors = true
hrefTargetBlank = true

[Languages]
[Languages.en]
title = "Building for Executives"
weight = 1
languageName = "English"

[[menu.shortcuts]]
name = "<i class='fab fa-github'></i> GitHub Project"
url = "https://github.com/MitchyBAwesome/aws-building-for-execs"
weight = 30